apiVersion: apps/v1
kind: Deployment
metadata:
  name: CO2App
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: CO2App
  template:
    metadata:
      labels:
        app: CO2App
    spec:
      containers:
      - name: CO2App
        image: nginx:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: refreshAPI
spec:
  schedule: "0 12 * * *"
  ttlSecondsAfterFinished: 100
  template:
    spec: 
      containers:
        - name: hh
          image: busybox
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

...