apiVersion: apps/v1
kind: Deployment
metadata:
  name: CO2App
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: CO2App
  template:
    metadata:
      labels:
        app: CO2App
    spec:
      containers:
      - name: CO2App
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
