name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        SUPER_SECRET: ${{ secrets.DOCKER_PASS }}
      run: |
        docker login -u dipugodocker -p "$SUPER_SECRET"
        docker build . --file Dockerfile --tag dipugodocker/co2app:$(date +%h)
        docker run dipugodocker/co2app:$(date +%h)
        docker push dipugodocker/co2app:$(date +%h)

...
