name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: 
        - docker login -u dipugodocker -p ${{DOCKER_PASS}}
        - docker build . --file Dockerfile --tag dipugodocker/co2app:$(date +%s)
        - docker push dipugodocker/co2app:$(date +%s)
